### ISSUE TITLE
Upgrade JGit to 5.X as 4.X no longer maintained

### ISSUE THREAD

**Issue by HiromuHota** [HiromuHota/pdi-git-plugin#40]
According to https://wiki.eclipse.org/JGit/New_and_Noteworthy, 4.X hasn't been updated since 4.11 (2018-03-08).

**Comment by HiromuHota** [comment]
JGit 5.6 and higher is not compatible with PDI 9.0 due to version mismatch on their dependency.
JGit 5.6 and higher uses version 1.64 of bouncycastle (https://projects.eclipse.org/projects/technology.jgit/releases/5.6.0/), while PDI 9.0 uses 1.38.

**Comment by HiromuHota** [comment]
Resolved by ecf44d3b42b4de9b33e2f38f332b3a58496eb14e, where JGit has been upgraded to 5.1.X.
5.2.X looks fine in terms of bouncycastle, but looks no longer maintained.

**Comment by HiromuHota** [comment]
The reason behind JGit's dependency on BouncyCastle as of v5.3 is that it started signing commits (https://bugs.eclipse.org/bugs/show_bug.cgi?id=382212).
Even though it is **optional** to sign commits, JGit tries to load `BouncyCastleGpgSigner` during CommitCommand, which causes the following error.
```
Caused by: java.lang.NoClassDefFoundError: org/bouncycastle/openpgp/PGPException
	at org.eclipse.jgit.lib.GpgSigner.<clinit>(GpgSigner.java:58)
	at org.eclipse.jgit.api.CommitCommand.processOptions(CommitCommand.java:611)
	at org.eclipse.jgit.api.CommitCommand.call(CommitCommand.java:195)
	at org.pentaho.di.git.spoon.model.UIGit.commit(UIGit.java:345)
	at org.pentaho.di.git.spoon.GitController.commit(GitController.java:614)
```

**Comment by HiromuHota** [comment]
PDI's dependecy on BouncyCastle 1.38 originates from pentaho-reporting.
```
org.pentaho.di:pdi-libs:pom:9.0.0.0-423-21
    pentaho-kettle:kettle-engine:jar:9.0.0.0-423-21:compile
       org.pentaho.reporting.engine:classic-core:jar:9.0.0.0-423:compile
          bouncycastle:bcprov-jdk14:jar:138:compile
          bouncycastle:bcmail-jdk14:jar:138:compile
```

and see https://github.com/pentaho/pentaho-reporting/blob/9.0.0.0-R/pom.xml#L100

**Comment by HiromuHota** [comment]
pentaho-reporting's dependency on BouncyCastle comes from its dependency on itext-rtf.
https://github.com/pentaho/pentaho-reporting/commit/85bb4ad2ab5ae5b355c2c5670b6cbf03091c112a

This seems like BouncyCastle will not be used in PDI as long as PDF is not produced as a report by pentaho-reporting.

**Comment by HiromuHota** [comment]
https://forums.pentaho.com/threads/128357-iText-Licensing/

**Comment by HiromuHota** [comment]
https://forums.pentaho.com/threads/223071-Itext-version-upgrade/
